// Code generated by sigil gen go. DO NOT EDIT.
//
// Kind AlertRouting version 1.

package alertrouting

import (
	"time"

	"github.com/spechtlabs/sigil/pkg/policy"
)

// Severity is the enum Severity of kind AlertRouting:
//
//	enum Severity: critical | warning | info
type Severity string

// The values of enum Severity, in declaration order.
const (
	SeverityCritical Severity = "critical"
	SeverityWarning  Severity = "warning"
	SeverityInfo     Severity = "info"
)

// Alert is the struct type Alert of kind AlertRouting.
type Alert struct {
	Name      string            `policy:"name"`       // name: string
	Severity  Severity          `policy:"severity"`   // severity: Severity
	Labels    map[string]string `policy:"labels"`     // labels: map<string, string>
	FiringFor time.Duration     `policy:"firing_for"` // firing_for: duration
}

// Team is the struct type Team of kind AlertRouting.
type Team struct {
	Name    string `policy:"name"`    // name: string
	Oncall  string `policy:"oncall"`  // oncall: string
	Channel string `policy:"channel"` // channel: string
}

// Input is the input of kind AlertRouting, the struct its policies
// evaluate: a policy reads each field by the name in its tag.
type Input struct {
	Alert Alert `policy:"alert"` // input alert: Alert
	Team  Team  `policy:"team"`  // input team: Team
}

// PageData is the payload of decision page, the case of a type switch on
// [policy.Result.Value] that matches it.
type PageData struct {
	Target string `policy:"target"` // target: string
}

// DropData is the payload of decision drop, the case of a type switch on
// [policy.Result.Value] that matches it.
type DropData struct{}

// NotifyData is the payload of decision notify, the case of a type switch
// on [policy.Result.Value] that matches it.
type NotifyData struct {
	Channel string `policy:"channel,default=\"#alerts\""` // channel: string = "#alerts"
}

// The decisions of kind AlertRouting, in precedence order, highest first.
var (
	// Page is decision page, with reason: critical_alert | sustained.
	Page = policy.NewDecision[PageData]("page", "critical_alert", "sustained")
	// Drop is decision drop, with reason: muted | not_production.
	Drop = policy.NewDecision[DropData]("drop", "muted", "not_production")
	// Notify is decision notify, with reason: routine | unrouted.
	Notify = policy.NewDecision[NotifyData]("notify", "routine", "unrouted")
)

// The reasons of the decisions, the handles a switch on [policy.Result.Why]
// compares against.
var (
	PageCriticalAlert = Page.Reason("critical_alert") // page(reason: critical_alert)
	PageSustained     = Page.Reason("sustained")      // page(reason: sustained)
	DropMuted         = Drop.Reason("muted")          // drop(reason: muted)
	DropNotProduction = Drop.Reason("not_production") // drop(reason: not_production)
	NotifyRoutine     = Notify.Reason("routine")      // notify(reason: routine)
	NotifyUnrouted    = Notify.Reason("unrouted")     // notify(reason: unrouted)
)

// NewKind builds kind AlertRouting, whose Schema() is the kind file this
// code was generated from, so it loads policies from a bundle that holds
// that file. Build it once.
//
// opts follow the options that declare the kind, for host behavior such as
// policy.WithRecoverHostPanics; an option that declares contract makes
// Schema() differ from the kind file.
func NewKind(opts ...policy.Option) *policy.Kind[Input] {
	return policy.NewKind[Input]("AlertRouting", append([]policy.Option{
		policy.WithVersion(1),
		policy.WithEnum(SeverityCritical, SeverityWarning, SeverityInfo),
		policy.WithDecisions(Page, Drop, Notify),
		policy.WithReasonPrecedence(PageCriticalAlert, PageSustained),
		policy.WithReasonPrecedence(DropMuted, DropNotProduction),
		policy.WithReasonPrecedence(NotifyRoutine, NotifyUnrouted),
		policy.WithDefault(NotifyUnrouted),
	}, opts...)...)
}
