// Code generated by sigil gen go. DO NOT EDIT.
//
// Kind AccessGrant version 1.

package accessgrant

import (
	"time"

	"github.com/spechtlabs/sigil/pkg/policy"
)

// Actor is the struct type Actor of kind AccessGrant.
type Actor struct {
	Name      string   `policy:"name"`      // name: string
	Groups    []string `policy:"groups"`    // groups: list<string>
	Clearance string   `policy:"clearance"` // clearance: string
}

// Input is the input of kind AccessGrant, the struct its policies evaluate:
// a policy reads each field by the name in its tag.
type Input struct {
	Actor       Actor  `policy:"actor"`       // input actor: Actor
	Team        string `policy:"team"`        // input team: string
	Environment string `policy:"environment"` // input environment: string
}

// ReaderData is the payload of decision reader, the case of a type switch
// on [policy.Result.Value] that matches it.
type ReaderData struct{}

// DeployerData is the payload of decision deployer, the case of a type
// switch on [policy.Result.Value] that matches it.
type DeployerData struct {
	TTL time.Duration `policy:"ttl,default=8h"` // ttl: duration = 8h
}

// ReleaseManagerData is the payload of decision release_manager, the case
// of a type switch on [policy.Result.Value] that matches it.
type ReleaseManagerData struct {
	TTL time.Duration `policy:"ttl,default=8h"` // ttl: duration = 8h
}

// AdminData is the payload of decision admin, the case of a type switch on
// [policy.Result.Value] that matches it.
type AdminData struct {
	TTL time.Duration `policy:"ttl,default=1h"` // ttl: duration = 1h
}

// AuditorData is the payload of decision auditor, the case of a type switch
// on [policy.Result.Value] that matches it.
type AuditorData struct{}

// The decisions of kind AccessGrant, in declaration order.
var (
	// Reader is decision reader, with reason: team_member |
	// everyone_in_staging.
	Reader = policy.NewDecision[ReaderData]("reader", "team_member", "everyone_in_staging")
	// Deployer is decision deployer, with reason: team_member | oncall.
	Deployer = policy.NewDecision[DeployerData]("deployer", "team_member", "oncall")
	// ReleaseManager is decision release_manager, with reason: platform_member.
	ReleaseManager = policy.NewDecision[ReleaseManagerData]("release_manager", "platform_member")
	// Admin is decision admin, with reason: clearance | break_glass.
	Admin = policy.NewDecision[AdminData]("admin", "clearance", "break_glass")
	// Auditor is decision auditor, with reason: compliance_member.
	Auditor = policy.NewDecision[AuditorData]("auditor", "compliance_member")
)

// The reasons of the decisions, the handles a switch on [policy.Result.Why]
// compares against.
var (
	ReaderTeamMember             = Reader.Reason("team_member")             // reader(reason: team_member)
	ReaderEveryoneInStaging      = Reader.Reason("everyone_in_staging")     // reader(reason: everyone_in_staging)
	DeployerTeamMember           = Deployer.Reason("team_member")           // deployer(reason: team_member)
	DeployerOncall               = Deployer.Reason("oncall")                // deployer(reason: oncall)
	ReleaseManagerPlatformMember = ReleaseManager.Reason("platform_member") // release_manager(reason: platform_member)
	AdminClearance               = Admin.Reason("clearance")                // admin(reason: clearance)
	AdminBreakGlass              = Admin.Reason("break_glass")              // admin(reason: break_glass)
	AuditorComplianceMember      = Auditor.Reason("compliance_member")      // auditor(reason: compliance_member)
)

// NewKind builds kind AccessGrant, whose Schema() is the kind file this
// code was generated from, so it loads policies from a bundle that holds
// that file. Build it once.
//
// opts follow the options that declare the kind, for host behavior such as
// policy.WithRecoverHostPanics; an option that declares contract makes
// Schema() differ from the kind file.
func NewKind(opts ...policy.Option) *policy.Kind[Input] {
	return policy.NewKind[Input]("AccessGrant", append([]policy.Option{
		policy.WithVersion(1),
		policy.WithCollect(Reader, Deployer, ReleaseManager, Admin, Auditor),
		policy.WithExclusive(Admin, ReleaseManager),
	}, opts...)...)
}
