package gogen

import (
	"fmt"
	"go/format"
	"slices"
	"strings"

	"github.com/spechtlabs/sigil/internal/ast"
	"github.com/spechtlabs/sigil/internal/check"
	"github.com/spechtlabs/sigil/internal/diag"
	"github.com/spechtlabs/sigil/internal/kind"
	"github.com/spechtlabs/sigil/internal/parser"
	"github.com/spechtlabs/sigil/internal/types"
)

// Header is the first line of every generated file, in the form Go
// tools recognize as generated code.
const Header = "// Code generated by sigil gen go. DO NOT EDIT."

// policyPath is the import path of package policy, which the generated
// code builds the kind with. The file always calls it policy: that is a
// Sigil keyword, so no struct type or enum of the kind takes the name.
const policyPath = "github.com/spechtlabs/sigil/pkg/policy"

// packageHelp says how to fix a package name Go rejects.
const packageHelp = "name another with --package, a Go identifier that isn't a keyword, like `deployapproval`"

// Options configures [Generate].
type Options struct {
	// Locate finds the declarations the diagnostics are about in the
	// kind file, as GenerateFile builds it from the kind file; nil leaves them without a
	// position.
	Locate kind.Locator
	// Package is the generated file's package name; empty means
	// [PackageName] of the kind.
	Package string
}

// generator is one Generate run: the kind, the Go names it gave every
// declaration, and the source it writes.
type generator struct {
	k       *kind.Kind
	locate  kind.Locator
	pkg     namespace                    // package-level identifiers already taken
	exact   map[string]string            // struct type and enum names, as Go writes them: the kind's own
	alias   map[string]string            // the exported alias of a struct type or enum whose name isn't exported
	values  map[string]map[string]string // enum name to its values' constants
	fields  map[string][]string          // struct type name to its fields' Go names
	reasons map[string]map[string]string // decision name to its reasons' handles
	payload map[string]string            // decision name to its payload type
	decVar  map[string]string            // decision name to its variable
	payFlds map[string][]string          // decision name to its payload fields' Go names
	name    string                       // the package name
	time    string                       // what the file calls package time; empty when it doesn't import it
	input   string                       // the input struct's name
	funcs   string                       // the Funcs struct's name; empty without host functions
	newKind string                       // the constructor's name
	inFlds  []string                     // the input struct's fields' Go names
	fnFlds  []string                     // the Funcs struct's fields' Go names
	errs    diag.ErrorList
	b       strings.Builder
}

// Generate returns a Go source file that declares k with package policy:
// the enums and struct types under the kind's names, the input struct, a
// payload struct of its own for every decision, a variable for every
// decision and every reason, and a constructor that builds the kind. The
// kind the constructor builds exports a kind file identical to k's
// [kind.Kind.Source], so it loads policies from a bundle that holds k's
// kind file. k must be valid.
//
// Generate fails when Go code can't declare k exactly: a struct type or
// enum named after a Go keyword or predeclared identifier, declarations
// in an order policy.NewKind can't produce, a struct type nothing uses, a
// `collect one` precedence other than the decisions' declaration order,
// or payload arguments on the default or the conflict outcome. It reports
// every problem, positioned with o.Locate, and returns nil source.
func Generate(k *kind.Kind, o Options) ([]byte, diag.ErrorList) {
	if k == nil {
		return nil, diag.ErrorList{{Msg: "no kind to generate code for"}}
	}
	g := &generator{
		k: k, locate: o.Locate, name: o.Package,
		pkg:   namespace{},
		exact: map[string]string{}, alias: map[string]string{},
		values: map[string]map[string]string{}, fields: map[string][]string{},
		reasons: map[string]map[string]string{}, payload: map[string]string{},
		decVar: map[string]string{}, payFlds: map[string][]string{},
	}
	if g.name == "" {
		g.name = PackageName(k.Name)
	}
	if err := CheckPackage(g.name); err != nil {
		if o.Package != "" {
			g.errs = append(g.errs, &diag.Error{Msg: err.Error(), Help: packageHelp})
		} else {
			g.errorf("kind", "the package is named after the kind; "+packageHelp, "%s", err.Error())
		}
	}
	g.expressible()
	if g.errs != nil {
		return nil, g.errs
	}
	g.allocate()
	g.file()
	src, err := format.Source([]byte(g.b.String()))
	if err != nil {
		// The generator writes only what it declared, so this is a bug in
		// it, not in the kind.
		return nil, diag.ErrorList{{Msg: "the generated code doesn't parse: " + err.Error(), Help: "this is a bug in sigil gen go; please report it with the kind file"}}
	}
	return src, nil
}

// GenerateFile loads the kind file src, read from file, and generates
// its Go code as [Generate] does, with o.Locate pointing into src. The
// kind is returned whenever the file loads, the diagnostics name file
// and come in source order, and those of a file that doesn't load are the kind loader's.
func GenerateFile(file string, src []byte, o Options) ([]byte, *kind.Kind, diag.ErrorList) {
	f, errs := parser.ParseFile(file, src)
	if errs != nil {
		return nil, nil, errs
	}
	c := check.New(file)
	k := c.KindFile(f)
	if k == nil {
		return nil, nil, c.Errors()
	}
	o.Locate = locate(f.Docs[0].(*ast.KindDoc))
	code, errs := Generate(k, o)
	for _, e := range errs {
		e.File = file
	}
	errs.Sort()
	return code, k, errs
}

// errorf records a problem with the declaration key names, as a
// [kind.Locator] keys it.
func (g *generator) errorf(key, help, msg string, args ...any) {
	e := &diag.Error{Msg: fmt.Sprintf(msg, args...), Help: help}
	if g.locate != nil {
		if start, end, ok := g.locate(key); ok {
			e.Pos, e.End = start, end
		}
	}
	g.errs = append(g.errs, e)
}

// allocate gives every declaration its Go name. The kind's struct types
// and enums keep their names, since the binding names a type after its
// Go type; everything else takes a name derived from the kind's, and
// when two derive the same one, the one declared earlier in this order
// keeps it and the later gets a number: the struct types' and enums'
// exported aliases, the input struct, Funcs and NewKind, the decisions
// with their payload types and reasons, and the enum values.
func (g *generator) allocate() {
	k := g.k
	for _, e := range k.Enums {
		g.exact[e.Name] = g.pkg.claim(e.Name)
	}
	for _, t := range k.Types {
		g.exact[t.Name] = g.pkg.claim(t.Name)
	}
	if g.usesTime() {
		g.time = g.pkg.claim("time", "gotime")
	}
	for _, e := range k.Enums {
		g.aliasFor(e.Name)
	}
	for _, t := range k.Types {
		g.aliasFor(t.Name)
	}
	g.input = g.pkg.claim("Input", GoName(k.Name)+"Input")
	if len(k.Funcs) > 0 {
		g.funcs = g.pkg.claim("Funcs")
	}
	g.newKind = g.pkg.claim("NewKind")
	for _, d := range k.Decisions {
		g.decVar[d.Name] = g.pkg.claim(GoName(d.Name))
		g.payload[d.Name] = g.pkg.claim(GoName(d.Name) + "Data")
		g.reasons[d.Name] = map[string]string{}
		for _, r := range d.Reasons {
			g.reasons[d.Name][r] = g.pkg.claim(GoName(d.Name) + GoName(r))
		}
		g.payFlds[d.Name] = fieldNames(len(d.Fields), func(i int) string { return d.Fields[i].Name })
	}
	for _, e := range k.Enums {
		g.values[e.Name] = map[string]string{}
		for _, v := range e.Values {
			g.values[e.Name][v] = g.pkg.claim(GoName(e.Name) + GoName(v))
		}
	}
	for _, t := range k.Types {
		g.fields[t.Name] = fieldNames(len(t.Fields), func(i int) string { return t.Fields[i].Name })
	}
	g.inFlds = fieldNames(len(k.Inputs), func(i int) string { return k.Inputs[i].Name })
	g.fnFlds = fieldNames(len(k.Funcs), func(i int) string { return k.Funcs[i].Name })
}

// aliasFor declares an exported alias for a struct type or enum whose
// name Go doesn't export, such as `service`, so code outside the
// generated package can name it.
func (g *generator) aliasFor(name string) {
	if c := name[0]; c < 'A' || c > 'Z' {
		g.alias[name] = g.pkg.claim(GoName(name))
	}
}

// fieldNames gives the n fields of one struct their Go names, the field
// Sigil name i returns run through [GoName], numbered where two collide.
func fieldNames(n int, name func(i int) string) []string {
	ns := namespace{}
	out := make([]string, n)
	for i := range n {
		out[i] = ns.claim(GoName(name(i)))
	}
	return out
}

// usesTime reports whether any declaration has a duration or a
// timestamp in its type, so the file imports package time.
func (g *generator) usesTime() bool {
	var uses func(t types.Type) bool
	uses = func(t types.Type) bool {
		switch t := t.(type) {
		case types.Basic:
			return t == types.Duration || t == types.Timestamp
		case *types.List:
			return uses(t.Elem)
		case *types.Map:
			return uses(t.Key) || uses(t.Value)
		case *types.Optional:
			return uses(t.Elem)
		}
		return false
	}
	k := g.k
	for _, t := range k.Types {
		for _, f := range t.Fields {
			if uses(f.Type) {
				return true
			}
		}
	}
	for _, in := range k.Inputs {
		if uses(in.Type) {
			return true
		}
	}
	for _, f := range k.Funcs {
		if uses(f.Result) || slices.ContainsFunc(f.Params, uses) {
			return true
		}
	}
	for _, d := range k.Decisions {
		for _, f := range d.Fields {
			if uses(f.Type) {
				return true
			}
		}
	}
	return false
}
