// Code generated by scripts/embed.ts from policies/platform/, policies/teams/ and
// src/lib/teams/teams.yaml. DO NOT EDIT; run `bun run generate`.

import type { SourceFile } from "@spechtlabs/sigil";

/** The platform's trusted documents: platform.alerts, platform.paging and platform.routing. */
export const PLATFORM_FILES: readonly SourceFile[] = [
  {
    path: "platform/alerts.sigil",
    source:
      'module platform.alerts: AlertRouting@1\n\npub let pre_production = alert.labels["env"] in ["staging", "dev"]\n',
  },
  {
    path: "platform/paging.sigil",
    source:
      "policy platform.paging: AlertRouting@1\n\nuse platform.alerts.{pre_production}\n\nparam page_after: duration = 30m, min: 5m, max: 1h\n\nwhen not pre_production and alert.severity == critical {\n  page(reason: critical_alert, target: team.oncall)\n}\n\nwhen not pre_production and alert.severity == warning and alert.firing_for >= page_after {\n  page(reason: sustained, target: team.oncall)\n}\n",
  },
  {
    path: "platform/routing.sigil",
    source:
      "policy platform.routing: AlertRouting@1\n\nuse platform.alerts.{pre_production}\n\nparam muted: list<string> = []\n\nwhen not pre_production and alert.severity == warning {\n  notify(reason: routine, channel: team.channel)\n}\n\nwhen pre_production {\n  drop(reason: not_production)\n}\n\nwhen alert.name in muted {\n  drop(reason: muted)\n}\n",
  },
];

/** The team bundle served when ALERTROUTER_POLICIES is empty. */
export const TEAM_FILES: readonly SourceFile[] = [
  {
    path: "checkout/alerts.sigil",
    source:
      'policy checkout.alerts: AlertRouting@1\n\nuse platform.alerts.{pre_production}\nuse platform.paging\nuse platform.routing\n\npaging(page_after: 10m)\n\nrouting(muted: ["CheckoutCanaryLatency"])\n\nwhen not pre_production and alert.severity == info and alert.labels["component"] == "payments" {\n  notify(reason: routine, channel: "#checkout-payments")\n}\n',
  },
  {
    path: "payments/alerts.sigil",
    source:
      'policy payments.alerts: AlertRouting@1\n\nuse platform.alerts.{pre_production}\nuse platform.paging\nuse platform.routing\n\npaging(page_after: 5m)\n\nrouting(muted: ["PaymentsSettlementBatchSlow"])\n\nwhen not pre_production and alert.severity == info and alert.labels["component"] == "ledger" {\n  notify(reason: routine, channel: "#payments-ledger")\n}\n',
  },
];

/** The team directory served when ALERTROUTER_TEAMS_FILE is empty. */
export const TEAMS_YAML: string =
  '# The team directory alertrouter ships with. An alert\'s team label picks the\n# entry, and the policy <name>.alerts decides with it. --teams-file (or\n# ALERTROUTER_TEAMS_FILE) replaces this file.\nteams:\n  - name: checkout\n    oncall: checkout-primary\n    channel: "#checkout-alerts"\n  - name: payments\n    oncall: payments-primary\n    channel: "#payments-alerts"\n';
