// Renders src/lib/embedded.ts from the files it embeds; shared by
// scripts/embed.ts, which writes it, and embedded.test.ts, which checks it.

import { readdir, readFile } from "node:fs/promises";
import { join, relative } from "node:path";

/** The directories and file embedded, relative to the example's root. */
export const EMBED = {
  platform: "policies/platform",
  teams: "policies/teams",
  teamsFile: "src/lib/teams/teams.yaml",
} as const;

/** The generated module's text, before formatting. */
export async function renderEmbedded(root: string): Promise<string> {
  const { platform, teams, teamsYaml } = await readEmbedded(root);
  return render(platform, teams, teamsYaml);
}

/** The embedded contents, read from the files they come from. */
export async function readEmbedded(root: string): Promise<{
  platform: { path: string; source: string }[];
  teams: { path: string; source: string }[];
  teamsYaml: string;
}> {
  // Platform paths keep their platform/ prefix, so a position in a trace
  // (checkout/alerts.sigil:8:1 → platform/routing.sigil:10:5) says which
  // side of the trust boundary a rule lives on. Team paths are relative to
  // the teams directory, as they are when read from ALERTROUTER_POLICIES.
  const platform = await sigilFiles(join(root, "policies"), join(root, EMBED.platform));
  const teams = await sigilFiles(join(root, EMBED.teams), join(root, EMBED.teams));
  const teamsYaml = await readFile(join(root, EMBED.teamsFile), "utf8");
  return { platform, teams, teamsYaml };
}

function render(platform: unknown, teams: unknown, teamsYaml: string): string {
  return `// Code generated by scripts/embed.ts from ${EMBED.platform}/, ${EMBED.teams}/ and
// ${EMBED.teamsFile}. DO NOT EDIT; run \`bun run generate\`.

import type { SourceFile } from "@spechtlabs/sigil";

/** The platform's trusted documents: platform.alerts, platform.paging and platform.routing. */
export const PLATFORM_FILES: readonly SourceFile[] = ${JSON.stringify(platform, null, 2)};

/** The team bundle served when ALERTROUTER_POLICIES is empty. */
export const TEAM_FILES: readonly SourceFile[] = ${JSON.stringify(teams, null, 2)};

/** The team directory served when ALERTROUTER_TEAMS_FILE is empty. */
export const TEAMS_YAML: string = ${JSON.stringify(teamsYaml)};
`;
}

async function sigilFiles(base: string, dir: string): Promise<{ path: string; source: string }[]> {
  const out: { path: string; source: string }[] = [];
  for (const e of (await readdir(dir, { withFileTypes: true })).sort((a, b) => (a.name < b.name ? -1 : 1))) {
    if (e.name.startsWith(".")) continue;
    const full = join(dir, e.name);
    if (e.isDirectory()) out.push(...(await sigilFiles(base, full)));
    else if (e.name.endsWith(".sigil")) out.push({ path: relative(base, full), source: await readFile(full, "utf8") });
  }
  return out;
}
