// Code generated by sigil gen go. DO NOT EDIT.
//
// Kind DeployApproval version 2.

package deployapproval

import (
	"time"

	"github.com/spechtlabs/sigil/pkg/policy"
)

// Tier is the enum Tier of kind DeployApproval:
//
//	enum Tier: critical | standard | internal
type Tier string

// The values of enum Tier, in declaration order.
const (
	TierCritical Tier = "critical"
	TierStandard Tier = "standard"
	TierInternal Tier = "internal"
)

// Release is the struct type Release of kind DeployApproval.
type Release struct {
	Soak   time.Duration `policy:"soak"`   // soak: duration
	Hotfix bool          `policy:"hotfix"` // hotfix: bool
}

// Service is the struct type Service of kind DeployApproval.
type Service struct {
	Name   string            `policy:"name"`   // name: string
	Tier   Tier              `policy:"tier"`   // tier: Tier
	Owners []string          `policy:"owners"` // owners: list<string>
	Labels map[string]string `policy:"labels"` // labels: map<string, string>
}

// Actor is the struct type Actor of kind DeployApproval.
type Actor struct {
	Name    string   `policy:"name"`    // name: string
	Teams   []string `policy:"teams"`   // teams: list<string>
	Roles   []string `policy:"roles"`   // roles: list<string>
	Regions []string `policy:"regions"` // regions: list<string>
}

// Freeze is the struct type Freeze of kind DeployApproval.
type Freeze struct {
	Environments []string `policy:"environments"` // environments: list<string>
	Unknown      bool     `policy:"unknown"`      // unknown: bool
}

// Input is the input of kind DeployApproval, the struct its policies
// evaluate: a policy reads each field by the name in its tag.
type Input struct {
	Release     Release `policy:"release"`     // input release: Release
	Service     Service `policy:"service"`     // input service: Service
	Actor       Actor   `policy:"actor"`       // input actor: Actor
	Environment string  `policy:"environment"` // input environment: string
	Freeze      Freeze  `policy:"freeze"`      // input freeze: Freeze
}

// DenyData is the payload of decision deny, the case of a type switch on
// [policy.Result.Value] that matches it.
type DenyData struct{}

// ReviewData is the payload of decision review, the case of a type switch
// on [policy.Result.Value] that matches it.
type ReviewData struct {
	Approvers []string `policy:"approvers"` // approvers: list<string>
}

// ApproveData is the payload of decision approve, the case of a type switch
// on [policy.Result.Value] that matches it.
type ApproveData struct {
	Bake time.Duration `policy:"bake,default=1h"` // bake: duration = 1h
}

// The decisions of kind DeployApproval, in precedence order, highest first.
var (
	// Deny is decision deny, with reason: not_eligible | change_freeze |
	// soak_too_short | no_rule_matched.
	Deny = policy.NewDecision[DenyData]("deny", "not_eligible", "change_freeze", "soak_too_short", "no_rule_matched")
	// Review is decision review, with reason: service_owner.
	Review = policy.NewDecision[ReviewData]("review", "service_owner")
	// Approve is decision approve, with reason: release_manager | payments_sre.
	Approve = policy.NewDecision[ApproveData]("approve", "release_manager", "payments_sre")
)

// The reasons of the decisions, the handles a switch on [policy.Result.Why]
// compares against.
var (
	DenyNotEligible       = Deny.Reason("not_eligible")       // deny(reason: not_eligible)
	DenyChangeFreeze      = Deny.Reason("change_freeze")      // deny(reason: change_freeze)
	DenySoakTooShort      = Deny.Reason("soak_too_short")     // deny(reason: soak_too_short)
	DenyNoRuleMatched     = Deny.Reason("no_rule_matched")    // deny(reason: no_rule_matched)
	ReviewServiceOwner    = Review.Reason("service_owner")    // review(reason: service_owner)
	ApproveReleaseManager = Approve.Reason("release_manager") // approve(reason: release_manager)
	ApprovePaymentsSre    = Approve.Reason("payments_sre")    // approve(reason: payments_sre)
)

// Funcs holds the implementations of the host functions kind DeployApproval
// declares, which NewKind takes. Every field must be set.
type Funcs struct {
	// Split implements fn split(string, string) -> list<string>.
	Split func(string, string) ([]string, error)
}

// NewKind builds kind DeployApproval, whose Schema() is the kind file this
// code was generated from, so it loads policies from a bundle that holds
// that file. Build it once.
//
// funcs implements the host functions, and NewKind panics when a field is
// nil. opts follow the options that declare the kind, for host behavior
// such as policy.WithRecoverHostPanics; an option that declares contract
// makes Schema() differ from the kind file.
func NewKind(funcs Funcs, opts ...policy.Option) *policy.Kind[Input] {
	missing := ""
	if funcs.Split == nil {
		missing += ", Funcs.Split"
	}
	if missing != "" {
		panic("deployapproval.NewKind: no implementation for host functions: " + missing[2:])
	}
	return policy.NewKind[Input]("DeployApproval", append([]policy.Option{
		policy.WithVersion(2),
		policy.WithEnum(TierCritical, TierStandard, TierInternal),
		policy.WithDecisions(Deny, Review, Approve),
		policy.WithReasonPrecedence(DenyNotEligible, DenyChangeFreeze, DenySoakTooShort, DenyNoRuleMatched),
		policy.WithReasonPrecedence(ApproveReleaseManager, ApprovePaymentsSre),
		policy.WithDefault(DenyNoRuleMatched),
		policy.WithFunc("split", funcs.Split),
	}, opts...)...)
}
