// Code generated by sigil gen go. DO NOT EDIT.
//
// Kind name_clash version 1.

package name_clash

import (
	gotime "time"

	"github.com/spechtlabs/sigil/pkg/policy"
)

// level is the enum level of kind name_clash:
//
//	enum level: low | high
type level string

// Level is enum level, under a name other packages can use.
type Level = level

// The values of enum level, in declaration order.
const (
	LevelLow2 level = "low"
	LevelHigh level = "high"
)

// time is the struct type time of kind name_clash.
type time struct {
	At gotime.Time `policy:"at"` // at: timestamp
}

// Time is struct type time, under a name other packages can use.
type Time = time

// Input is the struct type Input of kind name_clash.
type Input struct {
	UserID  string `policy:"user_id"` // user_id: string
	UserID2 string `policy:"userID"`  // userID: string
	X1      int64  `policy:"_1"`      // _1: int
	Type    string `policy:"type"`    // type: string
}

// NameClashInput is the input of kind name_clash, the struct its policies
// evaluate: a policy reads each field by the name in its tag.
type NameClashInput struct {
	When time  `policy:"when_"` // input when_: time
	User Input `policy:"user"`  // input user: Input
	Lvl  level `policy:"lvl"`   // input lvl: level
}

// LevelLowData is the payload of decision level_low, the case of a type
// switch on [policy.Result.Value] that matches it.
type LevelLowData struct{}

// NewKindData is the payload of decision new_kind, the case of a type
// switch on [policy.Result.Value] that matches it.
type NewKindData struct{}

// XData is the payload of decision x, the case of a type switch on
// [policy.Result.Value] that matches it.
type XData struct{}

// XDataData is the payload of decision x_data, the case of a type switch on
// [policy.Result.Value] that matches it.
type XDataData struct{}

// The decisions of kind name_clash, in declaration order.
var (
	// LevelLow is decision level_low, with reason: a | b.
	LevelLow = policy.NewDecision[LevelLowData]("level_low", "a", "b")
	// NewKind2 is decision new_kind, with reason: a.
	NewKind2 = policy.NewDecision[NewKindData]("new_kind", "a")
	// X is decision x, with reason: x_y.
	X = policy.NewDecision[XData]("x", "x_y")
	// XData2 is decision x_data, with reason: y.
	XData2 = policy.NewDecision[XDataData]("x_data", "y")
)

// The reasons of the decisions, the handles a switch on [policy.Result.Why]
// compares against.
var (
	LevelLowA = LevelLow.Reason("a") // level_low(reason: a)
	LevelLowB = LevelLow.Reason("b") // level_low(reason: b)
	NewKindA  = NewKind2.Reason("a") // new_kind(reason: a)
	XXY       = X.Reason("x_y")      // x(reason: x_y)
	XDataY    = XData2.Reason("y")   // x_data(reason: y)
)

// Funcs holds the implementations of the host functions kind name_clash
// declares, which NewKind takes. Every field must be set.
type Funcs struct {
	// GetURL implements fn get_url(string) -> string.
	GetURL func(string) (string, error)
	// GetURL2 implements fn getURL(string) -> string.
	GetURL2 func(string) (string, error)
}

// NewKind builds kind name_clash, whose Schema() is the kind file this code
// was generated from, so it loads policies from a bundle that holds that
// file. Build it once.
//
// funcs implements the host functions, and NewKind panics when a field is
// nil. opts follow the options that declare the kind, for host behavior
// such as policy.WithRecoverHostPanics; an option that declares contract
// makes Schema() differ from the kind file.
func NewKind(funcs Funcs, opts ...policy.Option) *policy.Kind[NameClashInput] {
	missing := ""
	if funcs.GetURL == nil {
		missing += ", Funcs.GetURL"
	}
	if funcs.GetURL2 == nil {
		missing += ", Funcs.GetURL2"
	}
	if missing != "" {
		panic("name_clash.NewKind: no implementation for host functions: " + missing[2:])
	}
	return policy.NewKind[NameClashInput]("name_clash", append([]policy.Option{
		policy.WithVersion(1),
		policy.WithEnum(LevelLow2, LevelHigh),
		policy.WithCollect(LevelLow, NewKind2, X, XData2),
		policy.WithPrecedence(XData2, X, NewKind2, LevelLow),
		policy.WithFunc("get_url", funcs.GetURL),
		policy.WithFunc("getURL", funcs.GetURL2),
	}, opts...)...)
}
