[
  (policy_document)
  (module_document)
  (kind_document)
  (block)
  (import_list)
  (field_list)
  (decision_body)
  (legacy_payload_list)
  (legacy_reason_list)
  (call_arguments)
  (arguments)
  (parameter_types)
  (list_literal)
  (map_literal)
  (raw_string)
] @fold
