// Code generated by sigil gen go. DO NOT EDIT.
//
// Kind RankedAccess version 2.

package rankedaccess

import "github.com/spechtlabs/sigil/pkg/policy"

// Actor is the struct type Actor of kind RankedAccess.
type Actor struct {
	Name string `policy:"name"` // name: string
}

// Input is the input of kind RankedAccess, the struct its policies
// evaluate: a policy reads each field by the name in its tag.
type Input struct {
	Actor Actor `policy:"actor"` // input actor: Actor
}

// WriteData is the payload of decision write, the case of a type switch on
// [policy.Result.Value] that matches it.
type WriteData struct {
	Scope []string `policy:"scope,default=[]"` // scope: list<string> = []
}

// ReadData is the payload of decision read, the case of a type switch on
// [policy.Result.Value] that matches it.
type ReadData struct{}

// The decisions of kind RankedAccess, in declaration order.
var (
	// Write is decision write, with reason: owner | maintainer.
	Write = policy.NewDecision[WriteData]("write", "owner", "maintainer")
	// Read is decision read, with reason: member | public.
	Read = policy.NewDecision[ReadData]("read", "member", "public")
)

// The reasons of the decisions, the handles a switch on [policy.Result.Why]
// compares against.
var (
	WriteOwner      = Write.Reason("owner")      // write(reason: owner)
	WriteMaintainer = Write.Reason("maintainer") // write(reason: maintainer)
	ReadMember      = Read.Reason("member")      // read(reason: member)
	ReadPublic      = Read.Reason("public")      // read(reason: public)
)

// NewKind builds kind RankedAccess, whose Schema() is the kind file this
// code was generated from, so it loads policies from a bundle that holds
// that file. Build it once.
//
// opts follow the options that declare the kind, for host behavior such as
// policy.WithRecoverHostPanics; an option that declares contract makes
// Schema() differ from the kind file.
func NewKind(opts ...policy.Option) *policy.Kind[Input] {
	return policy.NewKind[Input]("RankedAccess", append([]policy.Option{
		policy.WithVersion(2),
		policy.WithCollect(Write, Read),
		policy.WithPrecedence(Write, Read),
		policy.WithReasonPrecedence(WriteOwner, WriteMaintainer),
		policy.WithExclusive(WriteOwner, ReadPublic),
		policy.WithDefault(ReadPublic),
	}, opts...)...)
}
