// Code generated by sigil gen go. DO NOT EDIT.
//
// Kind Shapes version 4, accepts: 2.

package shapes

import (
	"time"

	"github.com/spechtlabs/sigil/pkg/policy"
)

// Tier is the enum Tier of kind Shapes:
//
//	enum Tier: critical | standard | internal
type Tier string

// The values of enum Tier, in declaration order.
const (
	TierCritical Tier = "critical"
	TierStandard Tier = "standard"
	TierInternal Tier = "internal"
)

// Plan is the enum Plan of kind Shapes:
//
//	enum Plan: free | standard | enterprise
type Plan string

// The values of enum Plan, in declaration order.
const (
	PlanFree       Plan = "free"
	PlanStandard   Plan = "standard"
	PlanEnterprise Plan = "enterprise"
)

// Region is the enum Region of kind Shapes:
//
//	enum Region: eu | us
type Region string

// The values of enum Region, in declaration order.
const (
	RegionEu Region = "eu"
	RegionUs Region = "us"
)

// Unused is the enum Unused of kind Shapes:
//
//	enum Unused: spare | extra
type Unused string

// The values of enum Unused, in declaration order.
const (
	UnusedSpare Unused = "spare"
	UnusedExtra Unused = "extra"
)

// Service is the struct type Service of kind Shapes.
type Service struct {
	Tier     Tier                           `policy:"tier"`      // tier: Tier
	Nodes    []Node                         `policy:"nodes"`     // nodes: list<Node>
	ByRegion map[Region][]Node              `policy:"by_region"` // by_region: map<Region, list<Node>>
	Matrix   [][]int64                      `policy:"matrix"`    // matrix: list<list<int>>
	Nested   map[string]map[int64][]*Window `policy:"nested"`    // nested: map<string, map<int, list<?Window>>>
	Limits   map[Tier]float64               `policy:"limits"`    // limits: map<Tier, float>
	Windows  map[time.Time]time.Duration    `policy:"windows"`   // windows: map<timestamp, duration>
}

// Node is the struct type Node of kind Shapes.
type Node struct {
	Name   string   `policy:"name"`   // name: string
	Weight float64  `policy:"weight"` // weight: float
	Tags   []string `policy:"tags"`   // tags: list<string>
	Window *Window  `policy:"window"` // window: ?Window
	Plan   *Plan    `policy:"plan"`   // plan: ?Plan
}

// Window is the struct type Window of kind Shapes.
type Window struct {
	Start  time.Time     `policy:"start"`  // start: timestamp
	Length time.Duration `policy:"length"` // length: duration
}

// Empty is the struct type Empty of kind Shapes.
type Empty struct{}

// Input is the input of kind Shapes, the struct its policies evaluate: a
// policy reads each field by the name in its tag.
type Input struct {
	Service *Service        `policy:"service"` // input service: ?Service
	Plan    Plan            `policy:"plan"`    // input plan: Plan
	Count   int64           `policy:"count"`   // input count: int
	Ratio   float64         `policy:"ratio"`   // input ratio: float
	Since   time.Time       `policy:"since"`   // input since: timestamp
	Flags   map[bool]string `policy:"flags"`   // input flags: map<bool, string>
	Nothing Empty           `policy:"nothing"` // input nothing: Empty
}

// DenyData is the payload of decision deny, the case of a type switch on
// [policy.Result.Value] that matches it.
type DenyData struct{}

// GrantData is the payload of decision grant, the case of a type switch on
// [policy.Result.Value] that matches it.
type GrantData struct {
	TTL     time.Duration    `policy:"ttl,default=1h30m"`                                   // ttl: duration = 1h30m
	Plan    Plan             `policy:"plan,default=standard"`                               // plan: Plan = standard
	Tiers   []Tier           `policy:"tiers,default=[critical, internal]"`                  // tiers: list<Tier> = [critical, internal]
	Limits  map[string]int64 `policy:"limits,default={\"a\": 1, \"b\": 2}"`                 // limits: map<string, int> = {"a": 1, "b": 2}
	Ratio   float64          `policy:"ratio,default=0.5"`                                   // ratio: float = 0.5
	Owner   *string          `policy:"owner"`                                               // owner: ?string
	Note    string           "policy:\"note,default=\\\"say \\\\\\\"hi\\\\\\\" `now`\\\"\"" // note: string = "say \"hi\" `now`"
	Count   int64            `policy:"count,default=-3"`                                    // count: int = -3
	Enabled bool             `policy:"enabled,default=true"`                                // enabled: bool = true
}

// ReviewData is the payload of decision review, the case of a type switch
// on [policy.Result.Value] that matches it.
type ReviewData struct {
	Owners []string `policy:"owners"` // owners: list<string>
}

// The decisions of kind Shapes, in precedence order, highest first.
var (
	// Deny is decision deny, with reason: blocked | fallback | conflicting.
	Deny = policy.NewDecision[DenyData]("deny", "blocked", "fallback", "conflicting")
	// Grant is decision grant, with reason: approved | standing.
	Grant = policy.NewDecision[GrantData]("grant", "approved", "standing")
	// Review is decision review, with reason: needs_owner.
	Review = policy.NewDecision[ReviewData]("review", "needs_owner")
)

// The reasons of the decisions, the handles a switch on [policy.Result.Why]
// compares against.
var (
	DenyBlocked      = Deny.Reason("blocked")       // deny(reason: blocked)
	DenyFallback     = Deny.Reason("fallback")      // deny(reason: fallback)
	DenyConflicting  = Deny.Reason("conflicting")   // deny(reason: conflicting)
	GrantApproved    = Grant.Reason("approved")     // grant(reason: approved)
	GrantStanding    = Grant.Reason("standing")     // grant(reason: standing)
	ReviewNeedsOwner = Review.Reason("needs_owner") // review(reason: needs_owner)
)

// Funcs holds the implementations of the host functions kind Shapes
// declares, which NewKind takes. Every field must be set.
type Funcs struct {
	// Lookup implements fn lookup(Tier, list<Region>, ?string) -> map<string,
	// int>.
	Lookup func(Tier, []Region, *string) (map[string]int64, error)
	// Now implements fn now() -> timestamp.
	Now func() (time.Time, error)
}

// NewKind builds kind Shapes, whose Schema() is the kind file this code was
// generated from, so it loads policies from a bundle that holds that file.
// Build it once.
//
// funcs implements the host functions, and NewKind panics when a field is
// nil. opts follow the options that declare the kind, for host behavior
// such as policy.WithRecoverHostPanics; an option that declares contract
// makes Schema() differ from the kind file.
func NewKind(funcs Funcs, opts ...policy.Option) *policy.Kind[Input] {
	missing := ""
	if funcs.Lookup == nil {
		missing += ", Funcs.Lookup"
	}
	if funcs.Now == nil {
		missing += ", Funcs.Now"
	}
	if missing != "" {
		panic("shapes.NewKind: no implementation for host functions: " + missing[2:])
	}
	return policy.NewKind[Input]("Shapes", append([]policy.Option{
		policy.WithVersion(4),
		policy.WithAccepts(2),
		policy.WithEnum(TierCritical, TierStandard, TierInternal),
		policy.WithEnum(PlanFree, PlanStandard, PlanEnterprise),
		policy.WithEnum(RegionEu, RegionUs),
		policy.WithEnum(UnusedSpare, UnusedExtra),
		policy.WithDecisions(Deny, Grant, Review),
		policy.WithReasonPrecedence(DenyBlocked, DenyConflicting, DenyFallback),
		policy.WithExclusive(GrantApproved, Review),
		policy.WithDefault(DenyFallback),
		policy.WithConflict(DenyConflicting),
		policy.WithFunc("lookup", funcs.Lookup),
		policy.WithFunc("now", funcs.Now),
	}, opts...)...)
}
